/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Balloon: THREE.Mesh;
    };
    materials: {
        Ballon_co: THREE.MeshStandardMaterial;
    };
};

export function Ballon({ ...props }: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>();
    const { nodes, materials } = useGLTF("/models/ballon.glb") as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                    geometry={nodes.Balloon.geometry}
                    material={materials.Ballon_co}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/ballon.glb");
